setwd("/path/to/samples/")
library(mclogit)

m.1 <- read.delim("clustering_meta.txt", header=TRUE) #metadata with the kmeans groups
m.1$Study_ID<-as.factor(m.1$Study_ID)
m.1$InfectionStatusOG<-as.factor(m.1$InfectionStatusOG)
m.1$EverInfection<-as.factor(m.1$EverInfection)
m.1$Timepoint<-as.factor(m.1$Timepoint)
m.1$HIVStatus<-as.factor(m.1$HIVstatus)
m.1$Abx10days<-as.factor(m.1$Abx10days)
m.1$Person_Code<-as.factor(m.1$Person_Code)
m.1$kmeans.all<-as.factor(m.1$kmeans)
Subset1<-subset(m.1,kmeans.all =='2'|kmeans.all =='3'|kmeans.all =='4'|kmeans.all =='5'|kmeans.all == '6')
Subset2<-subset(m.1,kmeans.all =='3'|kmeans.all =='4'|kmeans.all =='5'|kmeans.all == '6')
Subset3<-subset(m.1,kmeans.all =='4'|kmeans.all =='5'|kmeans.all == '6')
Subset4<-subset(m.1,kmeans.all =='5'|kmeans.all == '6')
set.seed(123)
(comm.mblogit <- mblogit(kmeans.all~Person_Code+InfectionStatusOG+EverInfection+Timepoint+HIVStatus+Abx10days,  data = m.1, random=~1|Study_ID))
summary(comm.mblogit)
set.seed(123)
(comm.mblogit.subset1 <- mblogit(kmeans.all~Person_Code+InfectionStatusOG+EverInfection+Timepoint+HIVStatus+Abx10days,  data = Subset1, random=~1|Study_ID))
summary(comm.mblogit.subset1)
set.seed(123)
(comm.mblogit.subset2 <- mblogit(kmeans.all~Person_Code+InfectionStatusOG+EverInfection+Timepoint+HIVStatus+Abx10days,  data = Subset2, random=~1|Study_ID))
summary(comm.mblogit.subset2)
set.seed(123)
(comm.mblogit.subset3 <- mblogit(kmeans.all~Person_Code+InfectionStatusOG+EverInfection+Timepoint+HIVStatus+Abx10days,  data = Subset3, random=~1|Study_ID))
summary(comm.mblogit.subset3)
set.seed(123)
(comm.mblogit.subset4 <- mblogit(kmeans.all~Person_Code+InfectionStatusOG+EverInfection+Timepoint+HIVStatus+Abx10days,  data = Subset4, random=~1|Study_ID))
summary(comm.mblogit.subset4)

#Benjamini-Hochberg method was used to correct for multiple comparisons. 